import { POKEMON_EXP_RATE_TYPES } from "./consts.js";

export const pokemonData = {
  Bulbasaur: {
    number: 1,
    name: "Bulbasaur",
    hp: 45,
    attack: 49,
    def: 49,
    speed: 45,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Ivysaur: {
    number: 2,
    name: "Ivysaur",
    hp: 60,
    attack: 62,
    def: 63,
    speed: 60,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Venusaur: {
    number: 3,
    name: "Venusaur",
    hp: 80,
    attack: 82,
    def: 83,
    speed: 80,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Charmander: {
    number: 4,
    name: "Charmander",
    hp: 39,
    attack: 52,
    def: 43,
    speed: 65,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Charmeleon: {
    number: 5,
    name: "Charmeleon",
    hp: 58,
    attack: 64,
    def: 58,
    speed: 80,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Charizard: {
    number: 6,
    name: "Charizard",
    hp: 78,
    attack: 84,
    def: 78,
    speed: 100,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Squirtle: {
    number: 7,
    name: "Squirtle",
    hp: 44,
    attack: 48,
    def: 65,
    speed: 43,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Wartortle: {
    number: 8,
    name: "Wartortle",
    hp: 59,
    attack: 63,
    def: 80,
    speed: 58,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Blastoise: {
    number: 9,
    name: "Blastoise",
    hp: 79,
    attack: 83,
    def: 100,
    speed: 78,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Caterpie: {
    number: 10,
    name: "Caterpie",
    hp: 45,
    attack: 30,
    def: 35,
    speed: 45,
    special: 20,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Metapod: {
    number: 11,
    name: "Metapod",
    hp: 50,
    attack: 20,
    def: 55,
    speed: 30,
    special: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Butterfree: {
    number: 12,
    name: "Butterfree",
    hp: 60,
    attack: 45,
    def: 50,
    speed: 70,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Weedle: {
    number: 13,
    name: "Weedle",
    hp: 40,
    attack: 35,
    def: 30,
    speed: 50,
    special: 20,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kakuna: {
    number: 14,
    name: "Kakuna",
    hp: 45,
    attack: 25,
    def: 50,
    speed: 35,
    special: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Beedrill: {
    number: 15,
    name: "Beedrill",
    hp: 65,
    attack: 80,
    def: 40,
    speed: 75,
    special: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Pidgey: {
    number: 16,
    name: "Pidgey",
    hp: 40,
    attack: 45,
    def: 40,
    speed: 56,
    special: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Pidgeotto: {
    number: 17,
    name: "Pidgeotto",
    hp: 63,
    attack: 60,
    def: 55,
    speed: 71,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Pidgeot: {
    number: 18,
    name: "Pidgeot",
    hp: 83,
    attack: 80,
    def: 75,
    speed: 91,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Rattata: {
    number: 19,
    name: "Rattata",
    hp: 30,
    attack: 56,
    def: 35,
    speed: 72,
    special: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Raticate: {
    number: 20,
    name: "Raticate",
    hp: 55,
    attack: 81,
    def: 60,
    speed: 97,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Spearow: {
    number: 21,
    name: "Spearow",
    hp: 40,
    attack: 60,
    def: 30,
    speed: 70,
    special: 31,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Fearow: {
    number: 22,
    name: "Fearow",
    hp: 65,
    attack: 90,
    def: 65,
    speed: 100,
    special: 61,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Ekans: {
    number: 23,
    name: "Ekans",
    hp: 35,
    attack: 60,
    def: 44,
    speed: 55,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Arbok: {
    number: 24,
    name: "Arbok",
    hp: 60,
    attack: 85,
    def: 69,
    speed: 80,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Pikachu: {
    number: 25,
    name: "Pikachu",
    hp: 35,
    attack: 55,
    def: 30,
    speed: 90,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Raichu: {
    number: 26,
    name: "Raichu",
    hp: 60,
    attack: 90,
    def: 55,
    speed: 100,
    special: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Sandshrew: {
    number: 27,
    name: "Sandshrew",
    hp: 50,
    attack: 75,
    def: 85,
    speed: 40,
    special: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Sandslash: {
    number: 28,
    name: "Sandslash",
    hp: 75,
    attack: 100,
    def: 110,
    speed: 65,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  "NidoranF": {
    number: 29,
    name: "Nidoran♀",
    hp: 55,
    attack: 47,
    def: 52,
    speed: 41,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidorina: {
    number: 30,
    name: "Nidorina",
    hp: 70,
    attack: 62,
    def: 67,
    speed: 56,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidoqueen: {
    number: 31,
    name: "Nidoqueen",
    hp: 90,
    attack: 82,
    def: 87,
    speed: 76,
    special: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  "NidoranM": {
    number: 32,
    name: "Nidoran♂",
    hp: 46,
    attack: 57,
    def: 40,
    speed: 50,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidorino: {
    number: 33,
    name: "Nidorino",
    hp: 61,
    attack: 72,
    def: 57,
    speed: 65,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidoking: {
    number: 34,
    name: "Nidoking",
    hp: 81,
    attack: 92,
    def: 77,
    speed: 85,
    special: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Clefairy: {
    number: 35,
    name: "Clefairy",
    hp: 70,
    attack: 45,
    def: 48,
    speed: 35,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Clefable: {
    number: 36,
    name: "Clefable",
    hp: 95,
    attack: 70,
    def: 73,
    speed: 60,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Vulpix: {
    number: 37,
    name: "Vulpix",
    hp: 38,
    attack: 41,
    def: 40,
    speed: 65,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Ninetales: {
    number: 38,
    name: "Ninetales",
    hp: 73,
    attack: 76,
    def: 75,
    speed: 100,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Jigglypuff: {
    number: 39,
    name: "Jigglypuff",
    hp: 115,
    attack: 45,
    def: 20,
    speed: 20,
    special: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Wigglytuff: {
    number: 40,
    name: "Wigglytuff",
    hp: 140,
    attack: 70,
    def: 45,
    speed: 45,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Zubat: {
    number: 41,
    name: "Zubat",
    hp: 40,
    attack: 45,
    def: 35,
    speed: 55,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Golbat: {
    number: 42,
    name: "Golbat",
    hp: 75,
    attack: 80,
    def: 70,
    speed: 90,
    special: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Oddish: {
    number: 43,
    name: "Oddish",
    hp: 45,
    attack: 50,
    def: 55,
    speed: 30,
    special: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Gloom: {
    number: 44,
    name: "Gloom",
    hp: 60,
    attack: 65,
    def: 70,
    speed: 40,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Vileplume: {
    number: 45,
    name: "Vileplume",
    hp: 75,
    attack: 80,
    def: 85,
    speed: 50,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Paras: {
    number: 46,
    name: "Paras",
    hp: 35,
    attack: 70,
    def: 55,
    speed: 25,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Parasect: {
    number: 47,
    name: "Parasect",
    hp: 60,
    attack: 95,
    def: 80,
    speed: 30,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Venonat: {
    number: 48,
    name: "Venonat",
    hp: 60,
    attack: 55,
    def: 50,
    speed: 45,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Venomoth: {
    number: 49,
    name: "Venomoth",
    hp: 70,
    attack: 65,
    def: 60,
    speed: 90,
    special: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Diglett: {
    number: 50,
    name: "Diglett",
    hp: 10,
    attack: 55,
    def: 25,
    speed: 95,
    special: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Dugtrio: {
    number: 51,
    name: "Dugtrio",
    hp: 35,
    attack: 80,
    def: 50,
    speed: 120,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Meowth: {
    number: 52,
    name: "Meowth",
    hp: 40,
    attack: 45,
    def: 35,
    speed: 90,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Persian: {
    number: 53,
    name: "Persian",
    hp: 65,
    attack: 70,
    def: 60,
    speed: 115,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Psyduck: {
    number: 54,
    name: "Psyduck",
    hp: 50,
    attack: 52,
    def: 48,
    speed: 55,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Golduck: {
    number: 55,
    name: "Golduck",
    hp: 80,
    attack: 82,
    def: 78,
    speed: 85,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Mankey: {
    number: 56,
    name: "Mankey",
    hp: 40,
    attack: 80,
    def: 35,
    speed: 70,
    special: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Primeape: {
    number: 57,
    name: "Primeape",
    hp: 65,
    attack: 105,
    def: 60,
    speed: 95,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Growlithe: {
    number: 58,
    name: "Growlithe",
    hp: 55,
    attack: 70,
    def: 45,
    speed: 60,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Arcanine: {
    number: 59,
    name: "Arcanine",
    hp: 90,
    attack: 110,
    def: 80,
    speed: 95,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Poliwag: {
    number: 60,
    name: "Poliwag",
    hp: 40,
    attack: 50,
    def: 40,
    speed: 90,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Poliwhirl: {
    number: 61,
    name: "Poliwhirl",
    hp: 65,
    attack: 65,
    def: 65,
    speed: 90,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Poliwrath: {
    number: 62,
    name: "Poliwrath",
    hp: 90,
    attack: 85,
    def: 95,
    speed: 70,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Abra: {
    number: 63,
    name: "Abra",
    hp: 25,
    attack: 20,
    def: 15,
    speed: 90,
    special: 105,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Kadabra: {
    number: 64,
    name: "Kadabra",
    hp: 40,
    attack: 35,
    def: 30,
    speed: 105,
    special: 120,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Alakazam: {
    number: 65,
    name: "Alakazam",
    hp: 55,
    attack: 50,
    def: 45,
    speed: 120,
    special: 135,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Machop: {
    number: 66,
    name: "Machop",
    hp: 70,
    attack: 80,
    def: 50,
    speed: 35,
    special: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Machoke: {
    number: 67,
    name: "Machoke",
    hp: 80,
    attack: 100,
    def: 70,
    speed: 45,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Machamp: {
    number: 68,
    name: "Machamp",
    hp: 90,
    attack: 130,
    def: 80,
    speed: 55,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Bellsprout: {
    number: 69,
    name: "Bellsprout",
    hp: 50,
    attack: 75,
    def: 35,
    speed: 40,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Weepinbell: {
    number: 70,
    name: "Weepinbell",
    hp: 65,
    attack: 90,
    def: 50,
    speed: 55,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Victreebel: {
    number: 71,
    name: "Victreebel",
    hp: 80,
    attack: 105,
    def: 65,
    speed: 70,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Tentacool: {
    number: 72,
    name: "Tentacool",
    hp: 40,
    attack: 40,
    def: 35,
    speed: 70,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Tentacruel: {
    number: 73,
    name: "Tentacruel",
    hp: 80,
    attack: 70,
    def: 65,
    speed: 100,
    special: 120,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Geodude: {
    number: 74,
    name: "Geodude",
    hp: 40,
    attack: 80,
    def: 100,
    speed: 20,
    special: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Graveler: {
    number: 75,
    name: "Graveler",
    hp: 55,
    attack: 95,
    def: 115,
    speed: 35,
    special: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Golem: {
    number: 76,
    name: "Golem",
    hp: 80,
    attack: 110,
    def: 130,
    speed: 45,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Ponyta: {
    number: 77,
    name: "Ponyta",
    hp: 50,
    attack: 85,
    def: 55,
    speed: 90,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Rapidash: {
    number: 78,
    name: "Rapidash",
    hp: 65,
    attack: 100,
    def: 70,
    speed: 105,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Slowpoke: {
    number: 79,
    name: "Slowpoke",
    hp: 90,
    attack: 65,
    def: 65,
    speed: 15,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Slowbro: {
    number: 80,
    name: "Slowbro",
    hp: 95,
    attack: 75,
    def: 110,
    speed: 30,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Magnemite: {
    number: 81,
    name: "Magnemite",
    hp: 25,
    attack: 35,
    def: 70,
    speed: 45,
    special: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Magneton: {
    number: 82,
    name: "Magneton",
    hp: 50,
    attack: 60,
    def: 95,
    speed: 70,
    special: 120,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  "Farfetchd": {
    number: 83,
    name: "Farfetch'd",
    hp: 52,
    attack: 65,
    def: 55,
    speed: 60,
    special: 58,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Doduo: {
    number: 84,
    name: "Doduo",
    hp: 35,
    attack: 85,
    def: 45,
    speed: 75,
    special: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Dodrio: {
    number: 85,
    name: "Dodrio",
    hp: 60,
    attack: 110,
    def: 70,
    speed: 100,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Seel: {
    number: 86,
    name: "Seel",
    hp: 65,
    attack: 45,
    def: 55,
    speed: 45,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Dewgong: {
    number: 87,
    name: "Dewgong",
    hp: 90,
    attack: 70,
    def: 80,
    speed: 70,
    special: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Grimer: {
    number: 88,
    name: "Grimer",
    hp: 80,
    attack: 80,
    def: 50,
    speed: 25,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Muk: {
    number: 89,
    name: "Muk",
    hp: 105,
    attack: 105,
    def: 75,
    speed: 50,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Shellder: {
    number: 90,
    name: "Shellder",
    hp: 30,
    attack: 65,
    def: 100,
    speed: 40,
    special: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Cloyster: {
    number: 91,
    name: "Cloyster",
    hp: 50,
    attack: 95,
    def: 180,
    speed: 70,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Gastly: {
    number: 92,
    name: "Gastly",
    hp: 30,
    attack: 35,
    def: 30,
    speed: 80,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Haunter: {
    number: 93,
    name: "Haunter",
    hp: 45,
    attack: 50,
    def: 45,
    speed: 95,
    special: 115,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Gengar: {
    number: 94,
    name: "Gengar",
    hp: 60,
    attack: 65,
    def: 60,
    speed: 110,
    special: 130,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Onix: {
    number: 95,
    name: "Onix",
    hp: 35,
    attack: 45,
    def: 160,
    speed: 70,
    special: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Drowzee: {
    number: 96,
    name: "Drowzee",
    hp: 60,
    attack: 48,
    def: 45,
    speed: 42,
    special: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Hypno: {
    number: 97,
    name: "Hypno",
    hp: 85,
    attack: 73,
    def: 70,
    speed: 67,
    special: 115,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Krabby: {
    number: 98,
    name: "Krabby",
    hp: 30,
    attack: 105,
    def: 90,
    speed: 50,
    special: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kingler: {
    number: 99,
    name: "Kingler",
    hp: 55,
    attack: 130,
    def: 115,
    speed: 75,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Voltorb: {
    number: 100,
    name: "Voltorb",
    hp: 40,
    attack: 30,
    def: 50,
    speed: 100,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Electrode: {
    number: 101,
    name: "Electrode",
    hp: 60,
    attack: 50,
    def: 70,
    speed: 140,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Exeggcute: {
    number: 102,
    name: "Exeggcute",
    hp: 60,
    attack: 40,
    def: 80,
    speed: 40,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Exeggutor: {
    number: 103,
    name: "Exeggutor",
    hp: 95,
    attack: 95,
    def: 85,
    speed: 55,
    special: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Cubone: {
    number: 104,
    name: "Cubone",
    hp: 50,
    attack: 50,
    def: 95,
    speed: 35,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Marowak: {
    number: 105,
    name: "Marowak",
    hp: 60,
    attack: 80,
    def: 110,
    speed: 45,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Hitmonlee: {
    number: 106,
    name: "Hitmonlee",
    hp: 50,
    attack: 120,
    def: 53,
    speed: 87,
    special: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Hitmonchan: {
    number: 107,
    name: "Hitmonchan",
    hp: 50,
    attack: 105,
    def: 79,
    speed: 76,
    special: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Lickitung: {
    number: 108,
    name: "Lickitung",
    hp: 90,
    attack: 55,
    def: 75,
    speed: 30,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Koffing: {
    number: 109,
    name: "Koffing",
    hp: 40,
    attack: 65,
    def: 95,
    speed: 35,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Weezing: {
    number: 110,
    name: "Weezing",
    hp: 65,
    attack: 90,
    def: 120,
    speed: 60,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Rhyhorn: {
    number: 111,
    name: "Rhyhorn",
    hp: 80,
    attack: 85,
    def: 95,
    speed: 25,
    special: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Rhydon: {
    number: 112,
    name: "Rhydon",
    hp: 105,
    attack: 130,
    def: 120,
    speed: 40,
    special: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Chansey: {
    number: 113,
    name: "Chansey",
    hp: 250,
    attack: 5,
    def: 5,
    speed: 50,
    special: 105,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Tangela: {
    number: 114,
    name: "Tangela",
    hp: 65,
    attack: 55,
    def: 115,
    speed: 60,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kangaskhan: {
    number: 115,
    name: "Kangaskhan",
    hp: 105,
    attack: 95,
    def: 80,
    speed: 90,
    special: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Horsea: {
    number: 116,
    name: "Horsea",
    hp: 30,
    attack: 40,
    def: 70,
    speed: 60,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Seadra: {
    number: 117,
    name: "Seadra",
    hp: 55,
    attack: 65,
    def: 95,
    speed: 85,
    special: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Goldeen: {
    number: 118,
    name: "Goldeen",
    hp: 45,
    attack: 67,
    def: 60,
    speed: 63,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Seaking: {
    number: 119,
    name: "Seaking",
    hp: 80,
    attack: 92,
    def: 65,
    speed: 68,
    special: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Staryu: {
    number: 120,
    name: "Staryu",
    hp: 30,
    attack: 45,
    def: 55,
    speed: 85,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Starmie: {
    number: 121,
    name: "Starmie",
    hp: 60,
    attack: 75,
    def: 85,
    speed: 115,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  MrMime: {
    number: 122,
    name: "Mr. Mime",
    hp: 40,
    attack: 45,
    def: 65,
    speed: 90,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Scyther: {
    number: 123,
    name: "Scyther",
    hp: 70,
    attack: 110,
    def: 80,
    speed: 105,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Jynx: {
    number: 124,
    name: "Jynx",
    hp: 65,
    attack: 50,
    def: 35,
    speed: 95,
    special: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Electabuzz: {
    number: 125,
    name: "Electabuzz",
    hp: 65,
    attack: 83,
    def: 57,
    speed: 105,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Magmar: {
    number: 126,
    name: "Magmar",
    hp: 65,
    attack: 95,
    def: 57,
    speed: 93,
    special: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Pinsir: {
    number: 127,
    name: "Pinsir",
    hp: 65,
    attack: 125,
    def: 100,
    speed: 85,
    special: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Tauros: {
    number: 128,
    name: "Tauros",
    hp: 75,
    attack: 100,
    def: 95,
    speed: 110,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Magikarp: {
    number: 129,
    name: "Magikarp",
    hp: 20,
    attack: 10,
    def: 55,
    speed: 80,
    special: 20,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Gyarados: {
    number: 130,
    name: "Gyarados",
    hp: 95,
    attack: 125,
    def: 79,
    speed: 81,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Lapras: {
    number: 131,
    name: "Lapras",
    hp: 130,
    attack: 85,
    def: 80,
    speed: 60,
    special: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Ditto: {
    number: 132,
    name: "Ditto",
    hp: 48,
    attack: 48,
    def: 48,
    speed: 48,
    special: 48,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Eevee: {
    number: 133,
    name: "Eevee",
    hp: 55,
    attack: 55,
    def: 50,
    speed: 55,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Vaporeon: {
    number: 134,
    name: "Vaporeon",
    hp: 130,
    attack: 65,
    def: 60,
    speed: 65,
    special: 110,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Jolteon: {
    number: 135,
    name: "Jolteon",
    hp: 65,
    attack: 65,
    def: 60,
    speed: 130,
    special: 110,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Flareon: {
    number: 136,
    name: "Flareon",
    hp: 65,
    attack: 130,
    def: 60,
    speed: 65,
    special: 110,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Porygon: {
    number: 137,
    name: "Porygon",
    hp: 65,
    attack: 60,
    def: 70,
    speed: 40,
    special: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Omanyte: {
    number: 138,
    name: "Omanyte",
    hp: 35,
    attack: 40,
    def: 100,
    speed: 35,
    special: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Omastar: {
    number: 139,
    name: "Omastar",
    hp: 70,
    attack: 60,
    def: 125,
    speed: 55,
    special: 115,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kabuto: {
    number: 140,
    name: "Kabuto",
    hp: 30,
    attack: 80,
    def: 90,
    speed: 55,
    special: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kabutops: {
    number: 141,
    name: "Kabutops",
    hp: 60,
    attack: 115,
    def: 105,
    speed: 80,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Aerodactyl: {
    number: 142,
    name: "Aerodactyl",
    hp: 80,
    attack: 105,
    def: 65,
    speed: 130,
    special: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Snorlax: {
    number: 143,
    name: "Snorlax",
    hp: 160,
    attack: 110,
    def: 65,
    speed: 30,
    special: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Articuno: {
    number: 144,
    name: "Articuno",
    hp: 90,
    attack: 85,
    def: 100,
    speed: 85,
    special: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Zapdos: {
    number: 145,
    name: "Zapdos",
    hp: 90,
    attack: 90,
    def: 85,
    speed: 100,
    special: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Moltres: {
    number: 146,
    name: "Moltres",
    hp: 90,
    attack: 100,
    def: 90,
    speed: 90,
    special: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Dratini: {
    number: 147,
    name: "Dratini",
    hp: 41,
    attack: 64,
    def: 45,
    speed: 50,
    special: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Dragonair: {
    number: 148,
    name: "Dragonair",
    hp: 61,
    attack: 84,
    def: 65,
    speed: 70,
    special: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Dragonite: {
    number: 149,
    name: "Dragonite",
    hp: 91,
    attack: 134,
    def: 95,
    speed: 80,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Mewtwo: {
    number: 150,
    name: "Mewtwo",
    hp: 106,
    attack: 110,
    def: 90,
    speed: 130,
    special: 154,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Mew: {
    number: 151,
    name: "Mew",
    hp: 100,
    attack: 100,
    def: 100,
    speed: 100,
    special: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
};
