import { POKEMON_EXP_RATE_TYPES } from "./consts.js";

export const pokemonData = {
  Bulbasaur: {
    number: 1,
    name: "Bulbasaur",
    baseHp: 45,
    baseAttack: 49,
    baseDef: 49,
    baseSpeed: 45,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Ivysaur: {
    number: 2,
    name: "Ivysaur",
    baseHp: 60,
    baseAttack: 62,
    baseDef: 63,
    baseSpeed: 60,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Venusaur: {
    number: 3,
    name: "Venusaur",
    baseHp: 80,
    baseAttack: 82,
    baseDef: 83,
    baseSpeed: 80,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Charmander: {
    number: 4,
    name: "Charmander",
    baseHp: 39,
    baseAttack: 52,
    baseDef: 43,
    baseSpeed: 65,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Charmeleon: {
    number: 5,
    name: "Charmeleon",
    baseHp: 58,
    baseAttack: 64,
    baseDef: 58,
    baseSpeed: 80,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Charizard: {
    number: 6,
    name: "Charizard",
    baseHp: 78,
    baseAttack: 84,
    baseDef: 78,
    baseSpeed: 100,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Squirtle: {
    number: 7,
    name: "Squirtle",
    baseHp: 44,
    baseAttack: 48,
    baseDef: 65,
    baseSpeed: 43,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Wartortle: {
    number: 8,
    name: "Wartortle",
    baseHp: 59,
    baseAttack: 63,
    baseDef: 80,
    baseSpeed: 58,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Blastoise: {
    number: 9,
    name: "Blastoise",
    baseHp: 79,
    baseAttack: 83,
    baseDef: 100,
    baseSpeed: 78,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Caterpie: {
    number: 10,
    name: "Caterpie",
    baseHp: 45,
    baseAttack: 30,
    baseDef: 35,
    baseSpeed: 45,
    baseSpecial: 20,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Metapod: {
    number: 11,
    name: "Metapod",
    baseHp: 50,
    baseAttack: 20,
    baseDef: 55,
    baseSpeed: 30,
    baseSpecial: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Butterfree: {
    number: 12,
    name: "Butterfree",
    baseHp: 60,
    baseAttack: 45,
    baseDef: 50,
    baseSpeed: 70,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Weedle: {
    number: 13,
    name: "Weedle",
    baseHp: 40,
    baseAttack: 35,
    baseDef: 30,
    baseSpeed: 50,
    baseSpecial: 20,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kakuna: {
    number: 14,
    name: "Kakuna",
    baseHp: 45,
    baseAttack: 25,
    baseDef: 50,
    baseSpeed: 35,
    baseSpecial: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Beedrill: {
    number: 15,
    name: "Beedrill",
    baseHp: 65,
    baseAttack: 80,
    baseDef: 40,
    baseSpeed: 75,
    baseSpecial: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Pidgey: {
    number: 16,
    name: "Pidgey",
    baseHp: 40,
    baseAttack: 45,
    baseDef: 40,
    baseSpeed: 56,
    baseSpecial: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Pidgeotto: {
    number: 17,
    name: "Pidgeotto",
    baseHp: 63,
    baseAttack: 60,
    baseDef: 55,
    baseSpeed: 71,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Pidgeot: {
    number: 18,
    name: "Pidgeot",
    baseHp: 83,
    baseAttack: 80,
    baseDef: 75,
    baseSpeed: 91,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Rattata: {
    number: 19,
    name: "Rattata",
    baseHp: 30,
    baseAttack: 56,
    baseDef: 35,
    baseSpeed: 72,
    baseSpecial: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Raticate: {
    number: 20,
    name: "Raticate",
    baseHp: 55,
    baseAttack: 81,
    baseDef: 60,
    baseSpeed: 97,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Spearow: {
    number: 21,
    name: "Spearow",
    baseHp: 40,
    baseAttack: 60,
    baseDef: 30,
    baseSpeed: 70,
    baseSpecial: 31,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Fearow: {
    number: 22,
    name: "Fearow",
    baseHp: 65,
    baseAttack: 90,
    baseDef: 65,
    baseSpeed: 100,
    baseSpecial: 61,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Ekans: {
    number: 23,
    name: "Ekans",
    baseHp: 35,
    baseAttack: 60,
    baseDef: 44,
    baseSpeed: 55,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Arbok: {
    number: 24,
    name: "Arbok",
    baseHp: 60,
    baseAttack: 85,
    baseDef: 69,
    baseSpeed: 80,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Pikachu: {
    number: 25,
    name: "Pikachu",
    baseHp: 35,
    baseAttack: 55,
    baseDef: 30,
    baseSpeed: 90,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Raichu: {
    number: 26,
    name: "Raichu",
    baseHp: 60,
    baseAttack: 90,
    baseDef: 55,
    baseSpeed: 100,
    baseSpecial: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Sandshrew: {
    number: 27,
    name: "Sandshrew",
    baseHp: 50,
    baseAttack: 75,
    baseDef: 85,
    baseSpeed: 40,
    baseSpecial: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Sandslash: {
    number: 28,
    name: "Sandslash",
    baseHp: 75,
    baseAttack: 100,
    baseDef: 110,
    baseSpeed: 65,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  NidoranF: {
    number: 29,
    name: "Nidoran♀",
    baseHp: 55,
    baseAttack: 47,
    baseDef: 52,
    baseSpeed: 41,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidorina: {
    number: 30,
    name: "Nidorina",
    baseHp: 70,
    baseAttack: 62,
    baseDef: 67,
    baseSpeed: 56,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidoqueen: {
    number: 31,
    name: "Nidoqueen",
    baseHp: 90,
    baseAttack: 82,
    baseDef: 87,
    baseSpeed: 76,
    baseSpecial: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  NidoranM: {
    number: 32,
    name: "Nidoran♂",
    baseHp: 46,
    baseAttack: 57,
    baseDef: 40,
    baseSpeed: 50,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidorino: {
    number: 33,
    name: "Nidorino",
    baseHp: 61,
    baseAttack: 72,
    baseDef: 57,
    baseSpeed: 65,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Nidoking: {
    number: 34,
    name: "Nidoking",
    baseHp: 81,
    baseAttack: 92,
    baseDef: 77,
    baseSpeed: 85,
    baseSpecial: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Clefairy: {
    number: 35,
    name: "Clefairy",
    baseHp: 70,
    baseAttack: 45,
    baseDef: 48,
    baseSpeed: 35,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Clefable: {
    number: 36,
    name: "Clefable",
    baseHp: 95,
    baseAttack: 70,
    baseDef: 73,
    baseSpeed: 60,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Vulpix: {
    number: 37,
    name: "Vulpix",
    baseHp: 38,
    baseAttack: 41,
    baseDef: 40,
    baseSpeed: 65,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Ninetales: {
    number: 38,
    name: "Ninetales",
    baseHp: 73,
    baseAttack: 76,
    baseDef: 75,
    baseSpeed: 100,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Jigglypuff: {
    number: 39,
    name: "Jigglypuff",
    baseHp: 115,
    baseAttack: 45,
    baseDef: 20,
    baseSpeed: 20,
    baseSpecial: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Wigglytuff: {
    number: 40,
    name: "Wigglytuff",
    baseHp: 140,
    baseAttack: 70,
    baseDef: 45,
    baseSpeed: 45,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Zubat: {
    number: 41,
    name: "Zubat",
    baseHp: 40,
    baseAttack: 45,
    baseDef: 35,
    baseSpeed: 55,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Golbat: {
    number: 42,
    name: "Golbat",
    baseHp: 75,
    baseAttack: 80,
    baseDef: 70,
    baseSpeed: 90,
    baseSpecial: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Oddish: {
    number: 43,
    name: "Oddish",
    baseHp: 45,
    baseAttack: 50,
    baseDef: 55,
    baseSpeed: 30,
    baseSpecial: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Gloom: {
    number: 44,
    name: "Gloom",
    baseHp: 60,
    baseAttack: 65,
    baseDef: 70,
    baseSpeed: 40,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Vileplume: {
    number: 45,
    name: "Vileplume",
    baseHp: 75,
    baseAttack: 80,
    baseDef: 85,
    baseSpeed: 50,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Paras: {
    number: 46,
    name: "Paras",
    baseHp: 35,
    baseAttack: 70,
    baseDef: 55,
    baseSpeed: 25,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Parasect: {
    number: 47,
    name: "Parasect",
    baseHp: 60,
    baseAttack: 95,
    baseDef: 80,
    baseSpeed: 30,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Venonat: {
    number: 48,
    name: "Venonat",
    baseHp: 60,
    baseAttack: 55,
    baseDef: 50,
    baseSpeed: 45,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Venomoth: {
    number: 49,
    name: "Venomoth",
    baseHp: 70,
    baseAttack: 65,
    baseDef: 60,
    baseSpeed: 90,
    baseSpecial: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Diglett: {
    number: 50,
    name: "Diglett",
    baseHp: 10,
    baseAttack: 55,
    baseDef: 25,
    baseSpeed: 95,
    baseSpecial: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Dugtrio: {
    number: 51,
    name: "Dugtrio",
    baseHp: 35,
    baseAttack: 80,
    baseDef: 50,
    baseSpeed: 120,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Meowth: {
    number: 52,
    name: "Meowth",
    baseHp: 40,
    baseAttack: 45,
    baseDef: 35,
    baseSpeed: 90,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Persian: {
    number: 53,
    name: "Persian",
    baseHp: 65,
    baseAttack: 70,
    baseDef: 60,
    baseSpeed: 115,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Psyduck: {
    number: 54,
    name: "Psyduck",
    baseHp: 50,
    baseAttack: 52,
    baseDef: 48,
    baseSpeed: 55,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Golduck: {
    number: 55,
    name: "Golduck",
    baseHp: 80,
    baseAttack: 82,
    baseDef: 78,
    baseSpeed: 85,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Mankey: {
    number: 56,
    name: "Mankey",
    baseHp: 40,
    baseAttack: 80,
    baseDef: 35,
    baseSpeed: 70,
    baseSpecial: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Primeape: {
    number: 57,
    name: "Primeape",
    baseHp: 65,
    baseAttack: 105,
    baseDef: 60,
    baseSpeed: 95,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Growlithe: {
    number: 58,
    name: "Growlithe",
    baseHp: 55,
    baseAttack: 70,
    baseDef: 45,
    baseSpeed: 60,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Arcanine: {
    number: 59,
    name: "Arcanine",
    baseHp: 90,
    baseAttack: 110,
    baseDef: 80,
    baseSpeed: 95,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Poliwag: {
    number: 60,
    name: "Poliwag",
    baseHp: 40,
    baseAttack: 50,
    baseDef: 40,
    baseSpeed: 90,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Poliwhirl: {
    number: 61,
    name: "Poliwhirl",
    baseHp: 65,
    baseAttack: 65,
    baseDef: 65,
    baseSpeed: 90,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Poliwrath: {
    number: 62,
    name: "Poliwrath",
    baseHp: 90,
    baseAttack: 85,
    baseDef: 95,
    baseSpeed: 70,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Abra: {
    number: 63,
    name: "Abra",
    baseHp: 25,
    baseAttack: 20,
    baseDef: 15,
    baseSpeed: 90,
    baseSpecial: 105,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Kadabra: {
    number: 64,
    name: "Kadabra",
    baseHp: 40,
    baseAttack: 35,
    baseDef: 30,
    baseSpeed: 105,
    baseSpecial: 120,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Alakazam: {
    number: 65,
    name: "Alakazam",
    baseHp: 55,
    baseAttack: 50,
    baseDef: 45,
    baseSpeed: 120,
    baseSpecial: 135,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Machop: {
    number: 66,
    name: "Machop",
    baseHp: 70,
    baseAttack: 80,
    baseDef: 50,
    baseSpeed: 35,
    baseSpecial: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Machoke: {
    number: 67,
    name: "Machoke",
    baseHp: 80,
    baseAttack: 100,
    baseDef: 70,
    baseSpeed: 45,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Machamp: {
    number: 68,
    name: "Machamp",
    baseHp: 90,
    baseAttack: 130,
    baseDef: 80,
    baseSpeed: 55,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Bellsprout: {
    number: 69,
    name: "Bellsprout",
    baseHp: 50,
    baseAttack: 75,
    baseDef: 35,
    baseSpeed: 40,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Weepinbell: {
    number: 70,
    name: "Weepinbell",
    baseHp: 65,
    baseAttack: 90,
    baseDef: 50,
    baseSpeed: 55,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Victreebel: {
    number: 71,
    name: "Victreebel",
    baseHp: 80,
    baseAttack: 105,
    baseDef: 65,
    baseSpeed: 70,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Tentacool: {
    number: 72,
    name: "Tentacool",
    baseHp: 40,
    baseAttack: 40,
    baseDef: 35,
    baseSpeed: 70,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Tentacruel: {
    number: 73,
    name: "Tentacruel",
    baseHp: 80,
    baseAttack: 70,
    baseDef: 65,
    baseSpeed: 100,
    baseSpecial: 120,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Geodude: {
    number: 74,
    name: "Geodude",
    baseHp: 40,
    baseAttack: 80,
    baseDef: 100,
    baseSpeed: 20,
    baseSpecial: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Graveler: {
    number: 75,
    name: "Graveler",
    baseHp: 55,
    baseAttack: 95,
    baseDef: 115,
    baseSpeed: 35,
    baseSpecial: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Golem: {
    number: 76,
    name: "Golem",
    baseHp: 80,
    baseAttack: 110,
    baseDef: 130,
    baseSpeed: 45,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Ponyta: {
    number: 77,
    name: "Ponyta",
    baseHp: 50,
    baseAttack: 85,
    baseDef: 55,
    baseSpeed: 90,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Rapidash: {
    number: 78,
    name: "Rapidash",
    baseHp: 65,
    baseAttack: 100,
    baseDef: 70,
    baseSpeed: 105,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Slowpoke: {
    number: 79,
    name: "Slowpoke",
    baseHp: 90,
    baseAttack: 65,
    baseDef: 65,
    baseSpeed: 15,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Slowbro: {
    number: 80,
    name: "Slowbro",
    baseHp: 95,
    baseAttack: 75,
    baseDef: 110,
    baseSpeed: 30,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Magnemite: {
    number: 81,
    name: "Magnemite",
    baseHp: 25,
    baseAttack: 35,
    baseDef: 70,
    baseSpeed: 45,
    baseSpecial: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Magneton: {
    number: 82,
    name: "Magneton",
    baseHp: 50,
    baseAttack: 60,
    baseDef: 95,
    baseSpeed: 70,
    baseSpecial: 120,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Farfetchd: {
    number: 83,
    name: "Farfetch'd",
    baseHp: 52,
    baseAttack: 65,
    baseDef: 55,
    baseSpeed: 60,
    baseSpecial: 58,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Doduo: {
    number: 84,
    name: "Doduo",
    baseHp: 35,
    baseAttack: 85,
    baseDef: 45,
    baseSpeed: 75,
    baseSpecial: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Dodrio: {
    number: 85,
    name: "Dodrio",
    baseHp: 60,
    baseAttack: 110,
    baseDef: 70,
    baseSpeed: 100,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Seel: {
    number: 86,
    name: "Seel",
    baseHp: 65,
    baseAttack: 45,
    baseDef: 55,
    baseSpeed: 45,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Dewgong: {
    number: 87,
    name: "Dewgong",
    baseHp: 90,
    baseAttack: 70,
    baseDef: 80,
    baseSpeed: 70,
    baseSpecial: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Grimer: {
    number: 88,
    name: "Grimer",
    baseHp: 80,
    baseAttack: 80,
    baseDef: 50,
    baseSpeed: 25,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Muk: {
    number: 89,
    name: "Muk",
    baseHp: 105,
    baseAttack: 105,
    baseDef: 75,
    baseSpeed: 50,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Shellder: {
    number: 90,
    name: "Shellder",
    baseHp: 30,
    baseAttack: 65,
    baseDef: 100,
    baseSpeed: 40,
    baseSpecial: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Cloyster: {
    number: 91,
    name: "Cloyster",
    baseHp: 50,
    baseAttack: 95,
    baseDef: 180,
    baseSpeed: 70,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Gastly: {
    number: 92,
    name: "Gastly",
    baseHp: 30,
    baseAttack: 35,
    baseDef: 30,
    baseSpeed: 80,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Haunter: {
    number: 93,
    name: "Haunter",
    baseHp: 45,
    baseAttack: 50,
    baseDef: 45,
    baseSpeed: 95,
    baseSpecial: 115,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Gengar: {
    number: 94,
    name: "Gengar",
    baseHp: 60,
    baseAttack: 65,
    baseDef: 60,
    baseSpeed: 110,
    baseSpecial: 130,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
  Onix: {
    number: 95,
    name: "Onix",
    baseHp: 35,
    baseAttack: 45,
    baseDef: 160,
    baseSpeed: 70,
    baseSpecial: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Drowzee: {
    number: 96,
    name: "Drowzee",
    baseHp: 60,
    baseAttack: 48,
    baseDef: 45,
    baseSpeed: 42,
    baseSpecial: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Hypno: {
    number: 97,
    name: "Hypno",
    baseHp: 85,
    baseAttack: 73,
    baseDef: 70,
    baseSpeed: 67,
    baseSpecial: 115,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Krabby: {
    number: 98,
    name: "Krabby",
    baseHp: 30,
    baseAttack: 105,
    baseDef: 90,
    baseSpeed: 50,
    baseSpecial: 25,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kingler: {
    number: 99,
    name: "Kingler",
    baseHp: 55,
    baseAttack: 130,
    baseDef: 115,
    baseSpeed: 75,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Voltorb: {
    number: 100,
    name: "Voltorb",
    baseHp: 40,
    baseAttack: 30,
    baseDef: 50,
    baseSpeed: 100,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Electrode: {
    number: 101,
    name: "Electrode",
    baseHp: 60,
    baseAttack: 50,
    baseDef: 70,
    baseSpeed: 140,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Exeggcute: {
    number: 102,
    name: "Exeggcute",
    baseHp: 60,
    baseAttack: 40,
    baseDef: 80,
    baseSpeed: 40,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Exeggutor: {
    number: 103,
    name: "Exeggutor",
    baseHp: 95,
    baseAttack: 95,
    baseDef: 85,
    baseSpeed: 55,
    baseSpecial: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Cubone: {
    number: 104,
    name: "Cubone",
    baseHp: 50,
    baseAttack: 50,
    baseDef: 95,
    baseSpeed: 35,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Marowak: {
    number: 105,
    name: "Marowak",
    baseHp: 60,
    baseAttack: 80,
    baseDef: 110,
    baseSpeed: 45,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Hitmonlee: {
    number: 106,
    name: "Hitmonlee",
    baseHp: 50,
    baseAttack: 120,
    baseDef: 53,
    baseSpeed: 87,
    baseSpecial: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Hitmonchan: {
    number: 107,
    name: "Hitmonchan",
    baseHp: 50,
    baseAttack: 105,
    baseDef: 79,
    baseSpeed: 76,
    baseSpecial: 35,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Lickitung: {
    number: 108,
    name: "Lickitung",
    baseHp: 90,
    baseAttack: 55,
    baseDef: 75,
    baseSpeed: 30,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Koffing: {
    number: 109,
    name: "Koffing",
    baseHp: 40,
    baseAttack: 65,
    baseDef: 95,
    baseSpeed: 35,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Weezing: {
    number: 110,
    name: "Weezing",
    baseHp: 65,
    baseAttack: 90,
    baseDef: 120,
    baseSpeed: 60,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Rhyhorn: {
    number: 111,
    name: "Rhyhorn",
    baseHp: 80,
    baseAttack: 85,
    baseDef: 95,
    baseSpeed: 25,
    baseSpecial: 30,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Rhydon: {
    number: 112,
    name: "Rhydon",
    baseHp: 105,
    baseAttack: 130,
    baseDef: 120,
    baseSpeed: 40,
    baseSpecial: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Chansey: {
    number: 113,
    name: "Chansey",
    baseHp: 250,
    baseAttack: 5,
    baseDef: 5,
    baseSpeed: 50,
    baseSpecial: 105,
    expRateType: POKEMON_EXP_RATE_TYPES.FAST,
  },
  Tangela: {
    number: 114,
    name: "Tangela",
    baseHp: 65,
    baseAttack: 55,
    baseDef: 115,
    baseSpeed: 60,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kangaskhan: {
    number: 115,
    name: "Kangaskhan",
    baseHp: 105,
    baseAttack: 95,
    baseDef: 80,
    baseSpeed: 90,
    baseSpecial: 40,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Horsea: {
    number: 116,
    name: "Horsea",
    baseHp: 30,
    baseAttack: 40,
    baseDef: 70,
    baseSpeed: 60,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Seadra: {
    number: 117,
    name: "Seadra",
    baseHp: 55,
    baseAttack: 65,
    baseDef: 95,
    baseSpeed: 85,
    baseSpecial: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Goldeen: {
    number: 118,
    name: "Goldeen",
    baseHp: 45,
    baseAttack: 67,
    baseDef: 60,
    baseSpeed: 63,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Seaking: {
    number: 119,
    name: "Seaking",
    baseHp: 80,
    baseAttack: 92,
    baseDef: 65,
    baseSpeed: 68,
    baseSpecial: 80,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Staryu: {
    number: 120,
    name: "Staryu",
    baseHp: 30,
    baseAttack: 45,
    baseDef: 55,
    baseSpeed: 85,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Starmie: {
    number: 121,
    name: "Starmie",
    baseHp: 60,
    baseAttack: 75,
    baseDef: 85,
    baseSpeed: 115,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  MrMime: {
    number: 122,
    name: "Mr. Mime",
    baseHp: 40,
    baseAttack: 45,
    baseDef: 65,
    baseSpeed: 90,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Scyther: {
    number: 123,
    name: "Scyther",
    baseHp: 70,
    baseAttack: 110,
    baseDef: 80,
    baseSpeed: 105,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Jynx: {
    number: 124,
    name: "Jynx",
    baseHp: 65,
    baseAttack: 50,
    baseDef: 35,
    baseSpeed: 95,
    baseSpecial: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Electabuzz: {
    number: 125,
    name: "Electabuzz",
    baseHp: 65,
    baseAttack: 83,
    baseDef: 57,
    baseSpeed: 105,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Magmar: {
    number: 126,
    name: "Magmar",
    baseHp: 65,
    baseAttack: 95,
    baseDef: 57,
    baseSpeed: 93,
    baseSpecial: 85,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Pinsir: {
    number: 127,
    name: "Pinsir",
    baseHp: 65,
    baseAttack: 125,
    baseDef: 100,
    baseSpeed: 85,
    baseSpecial: 55,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Tauros: {
    number: 128,
    name: "Tauros",
    baseHp: 75,
    baseAttack: 100,
    baseDef: 95,
    baseSpeed: 110,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Magikarp: {
    number: 129,
    name: "Magikarp",
    baseHp: 20,
    baseAttack: 10,
    baseDef: 55,
    baseSpeed: 80,
    baseSpecial: 20,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Gyarados: {
    number: 130,
    name: "Gyarados",
    baseHp: 95,
    baseAttack: 125,
    baseDef: 79,
    baseSpeed: 81,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Lapras: {
    number: 131,
    name: "Lapras",
    baseHp: 130,
    baseAttack: 85,
    baseDef: 80,
    baseSpeed: 60,
    baseSpecial: 95,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Ditto: {
    number: 132,
    name: "Ditto",
    baseHp: 48,
    baseAttack: 48,
    baseDef: 48,
    baseSpeed: 48,
    baseSpecial: 48,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Eevee: {
    number: 133,
    name: "Eevee",
    baseHp: 55,
    baseAttack: 55,
    baseDef: 50,
    baseSpeed: 55,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Vaporeon: {
    number: 134,
    name: "Vaporeon",
    baseHp: 130,
    baseAttack: 65,
    baseDef: 60,
    baseSpeed: 65,
    baseSpecial: 110,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Jolteon: {
    number: 135,
    name: "Jolteon",
    baseHp: 65,
    baseAttack: 65,
    baseDef: 60,
    baseSpeed: 130,
    baseSpecial: 110,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Flareon: {
    number: 136,
    name: "Flareon",
    baseHp: 65,
    baseAttack: 130,
    baseDef: 60,
    baseSpeed: 65,
    baseSpecial: 110,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Porygon: {
    number: 137,
    name: "Porygon",
    baseHp: 65,
    baseAttack: 60,
    baseDef: 70,
    baseSpeed: 40,
    baseSpecial: 75,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Omanyte: {
    number: 138,
    name: "Omanyte",
    baseHp: 35,
    baseAttack: 40,
    baseDef: 100,
    baseSpeed: 35,
    baseSpecial: 90,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Omastar: {
    number: 139,
    name: "Omastar",
    baseHp: 70,
    baseAttack: 60,
    baseDef: 125,
    baseSpeed: 55,
    baseSpecial: 115,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kabuto: {
    number: 140,
    name: "Kabuto",
    baseHp: 30,
    baseAttack: 80,
    baseDef: 90,
    baseSpeed: 55,
    baseSpecial: 45,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Kabutops: {
    number: 141,
    name: "Kabutops",
    baseHp: 60,
    baseAttack: 115,
    baseDef: 105,
    baseSpeed: 80,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_FAST,
  },
  Aerodactyl: {
    number: 142,
    name: "Aerodactyl",
    baseHp: 80,
    baseAttack: 105,
    baseDef: 65,
    baseSpeed: 130,
    baseSpecial: 60,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Snorlax: {
    number: 143,
    name: "Snorlax",
    baseHp: 160,
    baseAttack: 110,
    baseDef: 65,
    baseSpeed: 30,
    baseSpecial: 65,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Articuno: {
    number: 144,
    name: "Articuno",
    baseHp: 90,
    baseAttack: 85,
    baseDef: 100,
    baseSpeed: 85,
    baseSpecial: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Zapdos: {
    number: 145,
    name: "Zapdos",
    baseHp: 90,
    baseAttack: 90,
    baseDef: 85,
    baseSpeed: 100,
    baseSpecial: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Moltres: {
    number: 146,
    name: "Moltres",
    baseHp: 90,
    baseAttack: 100,
    baseDef: 90,
    baseSpeed: 90,
    baseSpecial: 125,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Dratini: {
    number: 147,
    name: "Dratini",
    baseHp: 41,
    baseAttack: 64,
    baseDef: 45,
    baseSpeed: 50,
    baseSpecial: 50,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Dragonair: {
    number: 148,
    name: "Dragonair",
    baseHp: 61,
    baseAttack: 84,
    baseDef: 65,
    baseSpeed: 70,
    baseSpecial: 70,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Dragonite: {
    number: 149,
    name: "Dragonite",
    baseHp: 91,
    baseAttack: 134,
    baseDef: 95,
    baseSpeed: 80,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Mewtwo: {
    number: 150,
    name: "Mewtwo",
    baseHp: 106,
    baseAttack: 110,
    baseDef: 90,
    baseSpeed: 130,
    baseSpecial: 154,
    expRateType: POKEMON_EXP_RATE_TYPES.SLOW,
  },
  Mew: {
    number: 151,
    name: "Mew",
    baseHp: 100,
    baseAttack: 100,
    baseDef: 100,
    baseSpeed: 100,
    baseSpecial: 100,
    expRateType: POKEMON_EXP_RATE_TYPES.MEDIUM_SLOW,
  },
};
